unit SRA411UM_P01;

interface

uses
  Windows, Messages, SysUtils, Variants, Classes, Graphics, Controls, Forms,
  Dialogs, DB, DBClient, QRCtrls, QuickRpt, ExtCtrls;

type
  TSRA411FM_P01 = class(TForm)
    qr_1: TQuickRep;
    PageHeaderBand1: TQRBand;
    QRLabel2: TQRLabel;
    TitleBand1: TQRBand;
    QRLabel3: TQRLabel;
    QRLabel4: TQRLabel;
    QRLabel5: TQRLabel;
    QRLabel6: TQRLabel;
    QRLabel8: TQRLabel;
    QRLabel9: TQRLabel;
    qrlb_Patno: TQRLabel;
    qrlb_Patnm: TQRLabel;
    qrlb_Wardno: TQRLabel;
    qrlb_SexAge: TQRLabel;
    qrlb_Meddept: TQRLabel;
    qrlb_Diagnm: TQRLabel;
    QRShape1: TQRShape;
    QRShape2: TQRShape;
    QRShape4: TQRShape;
    QRLabel15: TQRLabel;
    QRShape10: TQRShape;
    QRShape12: TQRShape;
    QRShape14: TQRShape;
    QRShape16: TQRShape;
    QRLabel20: TQRLabel;
    QRLabel22: TQRLabel;
    QRLabel23: TQRLabel;
    QRLabel55: TQRLabel;
    QRLabel64: TQRLabel;
    Q_cbx_medhisN: TQRShape;
    QRLabel65: TQRLabel;
    Q_cbx_medhisaspi: TQRShape;
    QRLabel67: TQRLabel;
    QRShape27: TQRShape;
    QRShape13: TQRShape;
    QRLabel99: TQRLabel;
    Q_ed_cdrecid1: TQRLabel;
    Q_ed_recid1: TQRLabel;
    cdSet: TClientDataSet;
    cdSetDRUGNM: TStringField;
    cdSetUSETYPE: TStringField;
    cdSetINJTM: TStringField;
    cdSetINJCAPA: TStringField;
    cdSetINJTM2: TStringField;
    cdSetINJCAPA2: TStringField;
    cdSetINJTM3: TStringField;
    cdSetINJCAPA3: TStringField;
    cdSetTOTALCAPA: TStringField;
    cdSetINJID: TStringField;
    cdSetDELWITH: TStringField;
    cdSetMONDATE: TStringField;
    Q_RadioButton1: TQRShape;
    QRLabel10: TQRLabel;
    Q_RadioButton2: TQRShape;
    QRLabel13: TQRLabel;
    QRShape3: TQRShape;
    QRLabel11: TQRLabel;
    QRLabel16: TQRLabel;
    QRLabel17: TQRLabel;
    QRLabel18: TQRLabel;
    QRLabel19: TQRLabel;
    QRLabel21: TQRLabel;
    QRLabel25: TQRLabel;
    QRLabel26: TQRLabel;
    Q_RadioButton3: TQRShape;
    Q_RadioButton6: TQRShape;
    Q_RadioButton12: TQRShape;
    Q_RadioButton9: TQRShape;
    Q_RadioButton24: TQRShape;
    Q_RadioButton21: TQRShape;
    Q_RadioButton18: TQRShape;
    Q_RadioButton15: TQRShape;
    QRLabel27: TQRLabel;
    QRLabel28: TQRLabel;
    QRLabel29: TQRLabel;
    QRLabel30: TQRLabel;
    QRLabel31: TQRLabel;
    QRLabel32: TQRLabel;
    QRLabel33: TQRLabel;
    QRLabel34: TQRLabel;
    Q_RadioButton4: TQRShape;
    QRLabel35: TQRLabel;
    Q_RadioButton7: TQRShape;
    Q_RadioButton10: TQRShape;
    Q_RadioButton13: TQRShape;
    Q_RadioButton25: TQRShape;
    Q_RadioButton22: TQRShape;
    Q_RadioButton19: TQRShape;
    Q_RadioButton16: TQRShape;
    QRLabel36: TQRLabel;
    QRLabel37: TQRLabel;
    QRLabel38: TQRLabel;
    QRLabel39: TQRLabel;
    QRLabel40: TQRLabel;
    QRLabel41: TQRLabel;
    QRLabel42: TQRLabel;
    Q_RadioButton5: TQRShape;
    QRLabel43: TQRLabel;
    Q_RadioButton8: TQRShape;
    Q_RadioButton11: TQRShape;
    Q_RadioButton14: TQRShape;
    Q_RadioButton26: TQRShape;
    Q_RadioButton23: TQRShape;
    Q_RadioButton20: TQRShape;
    Q_RadioButton17: TQRShape;
    QRLabel44: TQRLabel;
    QRLabel45: TQRLabel;
    QRLabel46: TQRLabel;
    QRLabel47: TQRLabel;
    QRLabel48: TQRLabel;
    QRLabel49: TQRLabel;
    QRLabel50: TQRLabel;
    QRLabel51: TQRLabel;
    QRLabel52: TQRLabel;
    QRLabel53: TQRLabel;
    QRLabel54: TQRLabel;
    QRLabel77: TQRLabel;
    QRLabel79: TQRLabel;
    QRLabel80: TQRLabel;
    QRLabel81: TQRLabel;
    Q_RadioButton27: TQRShape;
    QRLabel82: TQRLabel;
    Q_RadioButton28: TQRShape;
    QRLabel83: TQRLabel;
    Q_RadioButton29: TQRShape;
    QRLabel84: TQRLabel;
    Q_RadioButton30: TQRShape;
    QRLabel85: TQRLabel;
    Q_RadioButton31: TQRShape;
    QRLabel86: TQRLabel;
    Q_RadioButton32: TQRShape;
    QRLabel88: TQRLabel;
    Q_RadioButton33: TQRShape;
    QRLabel89: TQRLabel;
    Q_RadioButton34: TQRShape;
    QRLabel91: TQRLabel;
    Q_RadioButton35: TQRShape;
    QRLabel94: TQRLabel;
    QRLabel96: TQRLabel;
    Q_RadioButton38: TQRShape;
    QRLabel100: TQRLabel;
    Q_RadioButton37: TQRShape;
    QRLabel101: TQRLabel;
    Q_RadioButton36: TQRShape;
    Q_RadioButton39: TQRShape;
    QRLabel102: TQRLabel;
    Q_RadioButton40: TQRShape;
    QRLabel103: TQRLabel;
    Q_RadioButton41: TQRShape;
    QRLabel104: TQRLabel;
    Q_RadioButton42: TQRShape;
    QRLabel105: TQRLabel;
    Q_RadioButton43: TQRShape;
    QRLabel106: TQRLabel;
    Q_RadioButton44: TQRShape;
    QRLabel107: TQRLabel;
    QRLabel108: TQRLabel;
    Q_RadioButton47: TQRShape;
    QRLabel109: TQRLabel;
    Q_RadioButton46: TQRShape;
    Q_RadioButton45: TQRShape;
    QRLabel110: TQRLabel;
    Q_ed_Etc: TQRLabel;
    Q_rbt_allergyY: TQRShape;
    QRLabel57: TQRLabel;
    Q_rbt_allergyN: TQRShape;
    QRLabel58: TQRLabel;
    Q_ed_allergy: TQRLabel;
    QRShape11: TQRShape;
    Q_cbx_medhiswapa: TQRShape;
    QRLabel60: TQRLabel;
    Q_cbx_medhisetc: TQRShape;
    Q_ed_medhisetc: TQRLabel;
    QRLabel62: TQRLabel;
    QRLabel63: TQRLabel;
    QRLabel66: TQRLabel;
    Q_rbt_medaspiY: TQRShape;
    QRLabel68: TQRLabel;
    Q_rbt_medwapaY: TQRShape;
    QRLabel69: TQRLabel;
    Q_ed_medaspi: TQRLabel;
    QRLabel74: TQRLabel;
    Q_ed_medwapa: TQRLabel;
    QRLabel76: TQRLabel;
    Q_ed_medetc: TQRLabel;
    QRLabel90: TQRLabel;
    Q_rbt_medaspiN: TQRShape;
    QRLabel92: TQRLabel;
    Q_rbt_medwapaN: TQRShape;
    QRLabel93: TQRLabel;
    Q_rbt_medetcN: TQRShape;
    QRLabel95: TQRLabel;
    QRLabel97: TQRLabel;
    QRLabel98: TQRLabel;
    QRLabel111: TQRLabel;
    Q_RadioButton48: TQRShape;
    QRLabel112: TQRLabel;
    Q_RadioButton49: TQRShape;
    QRLabel113: TQRLabel;
    QRShape71: TQRShape;
    QRLabel114: TQRLabel;
    Q_RadioButton50: TQRShape;
    QRLabel115: TQRLabel;
    Q_RadioButton51: TQRShape;
    QRLabel116: TQRLabel;
    Q_CheckBox1: TQRShape;
    QRLabel117: TQRLabel;
    Q_CheckBox2: TQRShape;
    QRLabel118: TQRLabel;
    Q_CheckBox3: TQRShape;
    QRLabel119: TQRLabel;
    Q_CheckBox4: TQRShape;
    QRLabel120: TQRLabel;
    QRLabel121: TQRLabel;
    QRLabel122: TQRLabel;
    QRShape76: TQRShape;
    QRLabel123: TQRLabel;
    Q_RadioButton52: TQRShape;
    QRLabel124: TQRLabel;
    Q_RadioButton53: TQRShape;
    QRLabel125: TQRLabel;
    Q_RadioButton54: TQRShape;
    QRLabel126: TQRLabel;
    Q_RadioButton55: TQRShape;
    QRLabel127: TQRLabel;
    QRShape77: TQRShape;
    QRLabel128: TQRLabel;
    QRLabel129: TQRLabel;
    Q_RadioButton56: TQRShape;
    QRLabel130: TQRLabel;
    Q_RadioButton57: TQRShape;
    QRLabel131: TQRLabel;
    QRShape80: TQRShape;
    QRLabel132: TQRLabel;
    QRShape81: TQRShape;
    QRLabel133: TQRLabel;
    QRLabel134: TQRLabel;
    QRShape82: TQRShape;
    QRShape83: TQRShape;
    QRLabel138: TQRLabel;
    Q_mskEstmdate: TQRLabel;
    QRLabel139: TQRLabel;
    Q_ed_bph: TQRLabel;
    QRLabel140: TQRLabel;
    Q_ed_bpl: TQRLabel;
    QRLabel141: TQRLabel;
    Q_ed_pr: TQRLabel;
    QRLabel142: TQRLabel;
    QRLabel143: TQRLabel;
    Q_ed_rr: TQRLabel;
    QRLabel144: TQRLabel;
    Q_mm_Etc: TQRLabel;
    Q_rbt_medetcY: TQRShape;
    QRLabel7: TQRLabel;
    Q_RadioButton58: TQRShape;
    QRLabel56: TQRLabel;
    Q_RadioButton59: TQRShape;
    QRLabel59: TQRLabel;
    procedure FormClose(Sender: TObject; var Action: TCloseAction);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  SRA411FM_P01: TSRA411FM_P01;

implementation

{$R *.dfm}

procedure TSRA411FM_P01.FormClose(Sender: TObject;
  var Action: TCloseAction);
begin
  action := cafree;
  SRA411FM_P01 := nil;
end;

end.
